### ISSUE TITLE
Avoid print during Evaluation

### ISSUE THREAD

**Issue by JacopoRaffi** [UNEDLENAR/PyEvALL#2]
Sorry to annoy you again. I would like to know how to avoid the prints of the "evaluate" function of the class "PyEvALLEvaluation".

Thank you in advance for the answer

**Comment by jCarrilloDeAlbornoz** [comment]
Hi Jacopo,

You can manage the logger with the file.conf file in the utils package including a NullHandler. Nevertheless, I am working in a new version that allow  users to manage this with a parameter. I hope to have it ready next week. 

I hope this helps,
Regards

**Comment by JacopoRaffi** [comment]
Hi, 
Thank you very much for the answer.

Regards

**Comment by jCarrilloDeAlbornoz** [comment]
Done!
